module.exports = {
  someSidebar: {
    'Getting Started': ['overview', 'installation', 'quick_start'],
    Concepts: [
      'rj_object',
      'reducer',
      'computed_state_selectors',
      'action_creators',
      'side_effects',
      'effect_caller',
      'mutations',
      'consume_rj_objects',
      'plugin_system',
      'builder_mode',
      'logger',
    ],
    Plugins: [
      'plugin_intro',
      'plugin_list',
      'plugin_plain_list',
      'plugin_list_insert',
      'plugin_list_update',
      'plugin_list_delete',
      'plugin_map',
      'plugin_debounce',
      'plugin_cache',
      'plugin_mutations_pending',
    ],
    // Api: ['reference_rj', 'reference_use_rj'],
    Migrations: ['migration_from_2_to_3'],
  },
}
