export const INIT = '@@INIT'
export const RUN = 'RUN'
export const PENDING = 'PENDING'
export const SUCCESS = 'SUCCESS'
export const FAILURE = 'FAILURE'
export const CLEAN = 'CLEAN'
export const CANCEL = 'CANCEL'
